package com.cloderia.helion.client.shared.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * AccountTransaction generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = AccountTransaction.ALL_ACCOUNTTRANSACTION_QUERY, query = "SELECT e FROM AccountTransaction e ORDER BY e.id"),
  @NamedQuery(name = AccountTransaction.FIND_ACCOUNTTRANSACTION_BY_CODE_QUERY, query = "SELECT e FROM AccountTransaction e where e.entityCode = :entityCode ORDER  BY e.id"),
  @NamedQuery(name = AccountTransaction.FIND_ACCOUNTTRANSACTION_BY_TYPE_CODE_QUERY, query = "SELECT e FROM AccountTransaction e JOIN e.acctTxnType a where a.entityCode = :entityCode ORDER  BY e.id"),
})
@Table(name="accounttransaction")
public class AccountTransaction extends BaseEntity {

	private static final long serialVersionUID = 1L;
	public static final String ALL_ACCOUNTTRANSACTION_QUERY = "allAccountTransactions";
	public static final String FIND_ACCOUNTTRANSACTION_BY_CODE_QUERY = "findAccountTransactionsByCode";
	public static final String FIND_ACCOUNTTRANSACTION_BY_TYPE_CODE_QUERY = "findAccountTransactionsByTypeCode";
	
    private Integer id;

	private String entityCode;
    private BillingAccount billingAccount;
    private AccountTransactionType acctTxnType;
    private AccountTransactionStatus transactionStatus;
	private String name;
	private BigDecimal amount;
	private String dbCrFg;
	private Date dateCreated;
	private String description;

    public AccountTransaction() {
    }
	
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="billing_account", nullable=false)
    public BillingAccount getBillingAccount() {
        return this.billingAccount;
    }
    
    public void setBillingAccount(BillingAccount billingAccount) {
        this.billingAccount = billingAccount;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="acct_txn_type", nullable=false)
    public AccountTransactionType getAcctTxnType() {
        return this.acctTxnType;
    }
    
    public void setAcctTxnType(AccountTransactionType acctTxnType) {
        this.acctTxnType = acctTxnType;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="transaction_status", nullable=false)
    public AccountTransactionStatus getTransactionStatus() {
        return this.transactionStatus;
    }
    
    public void setTransactionStatus(AccountTransactionStatus transactionStatus) {
        this.transactionStatus = transactionStatus;
    }
    
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="amount", nullable=false, length=255)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
    @Column(name="db_cr_fg", nullable=true, length=255)
    public String getDbCrFg() {
        return this.dbCrFg;
    }
    
    public void setDbCrFg(String dbCrFg) {
        this.dbCrFg = dbCrFg;
    }
    
    @Column(name="date_created", nullable=false, length=35)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    
    @Column(name="description", nullable=false, length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

}


