package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Assignment generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Assignment.ALL_ASSIGNMENT_QUERY, query = "SELECT e FROM Assignment e ORDER BY e.id"),
  @NamedQuery(name = Assignment.FIND_ASSIGNMENT_BY_CODE_QUERY, query = "SELECT e FROM Assignment e where e.entityCode = :entityCode ORDER  BY e.id")
})
@Table(name="assignment")
public class Assignment extends BaseEntity {

	private static final long serialVersionUID = 1L;
	public static final String ALL_ASSIGNMENT_QUERY = "allAssignments";
	public static final String FIND_ASSIGNMENT_BY_CODE_QUERY = "findAssignmentsByCode";
	
    private Integer id;

	private String entityCode;
	@NotNull(message="The title is required.")
	private String name;
    private Classification docType;
    private Subject subject;
    private AcademicLevel alevel;
    private WritingStyle style;
    private Urgency urgency;
	@NotNull(message="The pages is required.")
	private Integer pageCount;
	@NotNull(message="The sources is required.")
	private Integer sourcesCount;
	private Date dateCreated;
	private Date dueDate;
	@NotNull(message="The description is required.")
	private String description;

    public Assignment() {
    }
	
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="doc_type", nullable=false)
    public Classification getDocType() {
        return this.docType;
    }
    
    public void setDocType(Classification docType) {
        this.docType = docType;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="subject", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="alevel", nullable=false)
    public AcademicLevel getAlevel() {
        return this.alevel;
    }
    
    public void setAlevel(AcademicLevel alevel) {
        this.alevel = alevel;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="style", nullable=false)
    public WritingStyle getStyle() {
        return this.style;
    }
    
    public void setStyle(WritingStyle style) {
        this.style = style;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="urgency", nullable=false)
    public Urgency getUrgency() {
        return this.urgency;
    }
    
    public void setUrgency(Urgency urgency) {
        this.urgency = urgency;
    }
    
    @Column(name="page_count", nullable=false, length=255)
    public Integer getPageCount() {
        return this.pageCount;
    }
    
    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }
    
    @Column(name="sources_count", nullable=false, length=255)
    public Integer getSourcesCount() {
        return this.sourcesCount;
    }
    
    public void setSourcesCount(Integer sourcesCount) {
        this.sourcesCount = sourcesCount;
    }
    
    @Column(name="date_created", nullable=false, length=35)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    
    @Column(name="due_date", nullable=false, length=35)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    
    @Lob 
    @Column(name="description", nullable=false, length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

}


