package com.cloderia.helion.client.shared.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * BillingAccount generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = BillingAccount.ALL_BILLINGACCOUNT_QUERY, query = "SELECT e FROM BillingAccount e ORDER BY e.id"),
  @NamedQuery(name = BillingAccount.FIND_BILLINGACCOUNT_BY_CODE_QUERY, query = "SELECT e FROM BillingAccount e where e.entityCode = :entityCode ORDER  BY e.id"),
})
@Table(name="billingaccount")
public class BillingAccount extends BaseEntity {

	private static final long serialVersionUID = 1L;
	public static final String ALL_BILLINGACCOUNT_QUERY = "allBillingAccounts";
	public static final String FIND_BILLINGACCOUNT_BY_CODE_QUERY = "findBillingAccountsByCode";
	
    private Integer id;

	private String entityCode;
    private Party bAccountParty;
	private String name;
	private BigDecimal balance;
	private Date dateCreated;
	private String description;

    public BillingAccount() {
    }
	
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="b_account_party", nullable=false)
    public Party getBAccountParty() {
        return this.bAccountParty;
    }
    
    public void setBAccountParty(Party bAccountParty) {
        this.bAccountParty = bAccountParty;
    }
    
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="balance", nullable=false, length=255)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }
    
    @Column(name="date_created", nullable=false, length=35)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    
    @Column(name="description", nullable=false, length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

}


