package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Classification generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Classification.ALL_CLASSIFICATION_QUERY, query = "SELECT e FROM Classification e ORDER BY e.id"),
  @NamedQuery(name = Classification.FIND_CLASSIFICATION_BY_CODE_QUERY, query = "SELECT e FROM Classification e where e.entityCode = :entityCode ORDER  BY e.id"),
  @NamedQuery(name = Classification.FIND_CLASSIFICATION_BY_TYPE_CODE_QUERY, query = "SELECT e FROM Classification e JOIN e.classType a where a.entityCode = :entityCode ORDER  BY e.id"),
})
@Table(name="classification")
public class Classification extends BaseEntity {

	private static final long serialVersionUID = 1L;
	public static final String ALL_CLASSIFICATION_QUERY = "allClassifications";
	public static final String FIND_CLASSIFICATION_BY_CODE_QUERY = "findClassificationsByCode";
	public static final String FIND_CLASSIFICATION_BY_TYPE_CODE_QUERY = "findClassificationsByTypeCode";
	
    private Integer id;

	private String entityCode;
    private ClassificationType classType;
	private String name;
	private Date dateCreated;
	private String description;

    public Classification() {
    }
	
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="entity_code", nullable=true, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="class_type", nullable=false)
    public ClassificationType getClassType() {
        return this.classType;
    }
    
    public void setClassType(ClassificationType classType) {
        this.classType = classType;
    }
    
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="date_created", nullable=false, length=35)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    
    @Column(name="description", nullable=false, length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

}


