package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Conversation generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Conversation.ALL_CONVERSATION_QUERY, query = "SELECT e FROM Conversation e ORDER BY e.id"),
  @NamedQuery(name = Conversation.FIND_CONVERSATION_BY_CODE_QUERY, query = "SELECT e FROM Conversation e where e.entityCode = :entityCode ORDER  BY e.id"),
  @NamedQuery(name = Conversation.FIND_CONVERSATION_BY_TYPE_CODE_QUERY, query = "SELECT e FROM Conversation e JOIN e.convType a where a.entityCode = :entityCode ORDER  BY e.id"),
})
@Table(name="conversation")
public class Conversation extends BaseEntity {

	private static final long serialVersionUID = 1L;
	public static final String ALL_CONVERSATION_QUERY = "allConversations";
	public static final String FIND_CONVERSATION_BY_CODE_QUERY = "findConversationsByCode";
	public static final String FIND_CONVERSATION_BY_TYPE_CODE_QUERY = "findConversationsByTypeCode";
	
    private Integer id;

	private String entityCode;
    private ConversationType convType;
	private String name;
	private String artifactCode;
	private String artifactName;
	private Date dateCreated;
	private String description;

    public Conversation() {
    }
	
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="conv_type", nullable=false)
    public ConversationType getConvType() {
        return this.convType;
    }
    
    public void setConvType(ConversationType convType) {
        this.convType = convType;
    }
    
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="artifact_code", nullable=true, length=35)
    public String getArtifactCode() {
        return this.artifactCode;
    }
    
    public void setArtifactCode(String artifactCode) {
        this.artifactCode = artifactCode;
    }
    
    @Column(name="artifact_name", nullable=true, length=255)
    public String getArtifactName() {
        return this.artifactName;
    }
    
    public void setArtifactName(String artifactName) {
        this.artifactName = artifactName;
    }
    
    @Column(name="date_created", nullable=false, length=35)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    
    @Column(name="description", nullable=false, length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

}


