package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * ConversationMessage generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = ConversationMessage.ALL_CONVERSATIONMESSAGE_QUERY, query = "SELECT e FROM ConversationMessage e ORDER BY e.id"),
  @NamedQuery(name = ConversationMessage.FIND_CONVERSATIONMESSAGE_BY_CODE_QUERY, query = "SELECT e FROM ConversationMessage e where e.entityCode = :entityCode ORDER  BY e.id"),
})
@Table(name="conversationmessage")
public class ConversationMessage extends BaseEntity {

	private static final long serialVersionUID = 1L;
	public static final String ALL_CONVERSATIONMESSAGE_QUERY = "allConversationMessages";
	public static final String FIND_CONVERSATIONMESSAGE_BY_CODE_QUERY = "findConversationMessagesByCode";
	
    private Integer id;

	private String entityCode;
    private Conversation msgConv;
    private Party toParty;
    private Party fromParty;
	private String name;
	private String artifactCode;
	private String artifactName;
	private String statusCode;
	private Date dateCreated;

    public ConversationMessage() {
    }
	
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="msg_conv", nullable=false)
    public Conversation getMsgConv() {
        return this.msgConv;
    }
    
    public void setMsgConv(Conversation msgConv) {
        this.msgConv = msgConv;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="to_party", nullable=false)
    public Party getToParty() {
        return this.toParty;
    }
    
    public void setToParty(Party toParty) {
        this.toParty = toParty;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="from_party", nullable=false)
    public Party getFromParty() {
        return this.fromParty;
    }
    
    public void setFromParty(Party fromParty) {
        this.fromParty = fromParty;
    }
    
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="artifact_code", nullable=true, length=35)
    public String getArtifactCode() {
        return this.artifactCode;
    }
    
    public void setArtifactCode(String artifactCode) {
        this.artifactCode = artifactCode;
    }
    
    @Column(name="artifact_name", nullable=true, length=255)
    public String getArtifactName() {
        return this.artifactName;
    }
    
    public void setArtifactName(String artifactName) {
        this.artifactName = artifactName;
    }
    
    @Column(name="status_code", nullable=true, length=35)
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }
    
    @Column(name="date_created", nullable=false, length=35)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

}


