package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * File generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = File.ALL_FILE_QUERY, query = "SELECT e FROM File e ORDER BY e.id"),
  @NamedQuery(name = File.FIND_FILE_BY_CODE_QUERY, query = "SELECT e FROM File e where e.entityCode = :entityCode ORDER  BY e.id"),
  @NamedQuery(name = File.FIND_FILE_BY_TYPE_CODE_QUERY, query = "SELECT e FROM File e JOIN e.fileType a where a.entityCode = :entityCode ORDER  BY e.id"),
})
@Table(name="file")
public class File extends BaseEntity {

	private static final long serialVersionUID = 1L;
	public static final String ALL_FILE_QUERY = "allFiles";
	public static final String FIND_FILE_BY_CODE_QUERY = "findFilesByCode";
	public static final String FIND_FILE_BY_TYPE_CODE_QUERY = "findFilesByTypeCode";
	
    private Integer id;

	private String entityCode;
    private FileType fileType;
	private String name;
	private String fileUrl;
	private String fileSize;
	private Date dateCreated;
	private String description;

    public File() {
    }
	
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="file_type", nullable=false)
    public FileType getFileType() {
        return this.fileType;
    }
    
    public void setFileType(FileType fileType) {
        this.fileType = fileType;
    }
    
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="file_url", nullable=false, length=255)
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }
    
    @Column(name="file_size", nullable=false, length=255)
    public String getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }
    
    @Column(name="date_created", nullable=false, length=35)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    
    @Column(name="description", nullable=false, length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

}


